//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 26-2-2020 16:28:32
namespace ProductsApp
{
    /// <summary>
    /// There are no comments for DefaultContainer in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DefaultContainer")]
    public partial class DefaultContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new DefaultContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public DefaultContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Demos", "ProductsApp");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("ProductsApp", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Demos.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Demos.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("cars")]
        public global::Microsoft.OData.Client.DataServiceQuery<Car> Cars
        {
            get
            {
                if ((this._Cars == null))
                {
                    this._Cars = base.CreateQuery<Car>("cars");
                }
                return this._Cars;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::Microsoft.OData.Client.DataServiceQuery<Car> _Cars;
        /// <summary>
        /// There are no comments for Cars in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public void AddToCars(Car car)
        {
            base.AddObject("cars", car);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Demos"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Car"">
        <Key>
          <PropertyRef Name=""ID"" />
        </Key>
        <Property Name=""ID"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""AmountMade"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""APK"" Type=""Edm.Boolean"" Nullable=""false"" />
        <Property Name=""Colour"" Type=""Edm.String"" />
        <Property Name=""TimeWhenAddedToDatabase"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""Brand"" Type=""Demos._Brands"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""_Brands"">
        <Member Name=""Audi"" Value=""6"" />
        <Member Name=""BMW"" Value=""9"" />
        <Member Name=""Ferrari"" Value=""1"" />
        <Member Name=""Ford"" Value=""7"" />
        <Member Name=""Honda"" Value=""8"" />
        <Member Name=""Mercedes"" Value=""10"" />
        <Member Name=""Mini"" Value=""2"" />
        <Member Name=""Nissan"" Value=""5"" />
        <Member Name=""Porsche"" Value=""3"" />
        <Member Name=""Tesla"" Value=""0"" />
        <Member Name=""Toyota"" Value=""11"" />
        <Member Name=""Volkswagen"" Value=""4"" />
      </EnumType>
      <EntityContainer Name=""DefaultContainer"">
        <EntitySet Name=""cars"" EntityType=""Demos.Car"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;
                    
                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for CarSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CarSingle")]
    public partial class CarSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Car>
    {
        /// <summary>
        /// Initialize a new CarSingle object.
        /// </summary>
        public CarSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CarSingle object.
        /// </summary>
        public CarSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CarSingle object.
        /// </summary>
        public CarSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Car> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Car in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("ID")]
    [global::Microsoft.OData.Client.EntitySet("cars")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Car")]
    public partial class Car : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Car object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="amountMade">Initial value of AmountMade.</param>
        /// <param name="aPK">Initial value of APK.</param>
        /// <param name="timeWhenAddedToDatabase">Initial value of TimeWhenAddedToDatabase.</param>
        /// <param name="brand">Initial value of Brand.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public static Car CreateCar(int ID, double amountMade, bool aPK, global::System.DateTimeOffset timeWhenAddedToDatabase, global::ProductsApp._Brands brand)
        {
            Car car = new Car();
            car.ID = ID;
            car.AmountMade = amountMade;
            car.APK = aPK;
            car.TimeWhenAddedToDatabase = timeWhenAddedToDatabase;
            car.Brand = brand;
            return car;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ID")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property AmountMade in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("AmountMade")]
        public double AmountMade
        {
            get
            {
                return this._AmountMade;
            }
            set
            {
                this.OnAmountMadeChanging(value);
                this._AmountMade = value;
                this.OnAmountMadeChanged();
                this.OnPropertyChanged("AmountMade");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private double _AmountMade;
        partial void OnAmountMadeChanging(double value);
        partial void OnAmountMadeChanged();
        /// <summary>
        /// There are no comments for Property APK in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("APK")]
        public bool APK
        {
            get
            {
                return this._APK;
            }
            set
            {
                this.OnAPKChanging(value);
                this._APK = value;
                this.OnAPKChanged();
                this.OnPropertyChanged("APK");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private bool _APK;
        partial void OnAPKChanging(bool value);
        partial void OnAPKChanged();
        /// <summary>
        /// There are no comments for Property Colour in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Colour")]
        public string Colour
        {
            get
            {
                return this._Colour;
            }
            set
            {
                this.OnColourChanging(value);
                this._Colour = value;
                this.OnColourChanged();
                this.OnPropertyChanged("Colour");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private string _Colour;
        partial void OnColourChanging(string value);
        partial void OnColourChanged();
        /// <summary>
        /// There are no comments for Property TimeWhenAddedToDatabase in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("TimeWhenAddedToDatabase")]
        public global::System.DateTimeOffset TimeWhenAddedToDatabase
        {
            get
            {
                return this._TimeWhenAddedToDatabase;
            }
            set
            {
                this.OnTimeWhenAddedToDatabaseChanging(value);
                this._TimeWhenAddedToDatabase = value;
                this.OnTimeWhenAddedToDatabaseChanged();
                this.OnPropertyChanged("TimeWhenAddedToDatabase");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::System.DateTimeOffset _TimeWhenAddedToDatabase;
        partial void OnTimeWhenAddedToDatabaseChanging(global::System.DateTimeOffset value);
        partial void OnTimeWhenAddedToDatabaseChanged();
        /// <summary>
        /// There are no comments for Property Brand in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Brand")]
        public global::ProductsApp._Brands Brand
        {
            get
            {
                return this._Brand;
            }
            set
            {
                this.OnBrandChanging(value);
                this._Brand = value;
                this.OnBrandChanged();
                this.OnPropertyChanged("Brand");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        private global::ProductsApp._Brands _Brand;
        partial void OnBrandChanging(global::ProductsApp._Brands value);
        partial void OnBrandChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "7.5.1")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for _Brands in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("_Brands")]
    public enum _Brands
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Audi")]
        Audi = 6,
        [global::Microsoft.OData.Client.OriginalNameAttribute("BMW")]
        BMW = 9,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ferrari")]
        Ferrari = 1,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Ford")]
        Ford = 7,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Honda")]
        Honda = 8,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Mercedes")]
        Mercedes = 10,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Mini")]
        Mini = 2,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Nissan")]
        Nissan = 5,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Porsche")]
        Porsche = 3,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tesla")]
        Tesla = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Toyota")]
        Toyota = 11,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Volkswagen")]
        Volkswagen = 4
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::ProductsApp.Car as global::ProductsApp.CarSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::ProductsApp.CarSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ProductsApp.Car> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::ProductsApp.CarSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::ProductsApp.Car as global::ProductsApp.CarSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="iD">The value of iD</param>
        public static global::ProductsApp.CarSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::ProductsApp.Car> source,
            int iD)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "ID", iD }
            };
            return new global::ProductsApp.CarSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
